### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by jceb** [SFTtech/xautocfg#5]
Could you create a new tag that includes these changes? I'm planning to submit a xautocfg package PR to NixOS that needs a tag to point to the right version. https://github.com/NixOS/nixpkgs/compare/master...identinet:nixpkgs:xautocfg-1.2

**Comment by TheJJ** [comment]
sure!

**Comment by TheJJ** [comment]
ok, we now have v1.2 :)
i've cleaned up the current implementation a bit, and added the XINPUTID environment variable to show the keyboard device id.

also i've renamed and move the config file entries for these scripts since in the current implementation they strictly apply to keyboard plugging, so a separate section for them doesn't seem right.
